[2024-07-11 13:12:24,506: INFO: demo: Welcome to the log]
[2024-07-13 12:42:44,451: INFO: demo: Welcome to the log test 2]
[2024-07-13 12:50:25,758: INFO: demo: Welcome to the log test 2]
[2024-07-13 12:50:35,375: INFO: demo: Welcome to the log test 2]
[2024-07-13 13:45:40,337: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-13 13:45:40,339: INFO: common: yaml file: params.yaml  loaded successfully]
[2024-07-13 13:45:40,340: INFO: common: created directory at: artifacts]
[2024-07-13 13:45:40,341: INFO: common: created directory at: artifacts/data_ingestion]
[2024-07-13 13:55:23,957: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-13 13:55:23,960: INFO: common: yaml file: params.yaml  loaded successfully]
[2024-07-13 13:55:23,961: INFO: common: created directory at: artifacts]
[2024-07-13 13:55:23,963: INFO: common: created directory at: artifacts/data_ingestion]
[2024-07-13 13:58:41,290: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-13 13:58:41,292: INFO: common: yaml file: params.yaml  loaded successfully]
[2024-07-13 13:58:41,293: INFO: common: created directory at: artifacts]
[2024-07-13 13:58:41,294: INFO: common: created directory at: artifacts/data_ingestion]
[2024-07-13 13:58:41,295: INFO: 1254779870: Downloading data from https://drive.google.com/file/d/11Ub5SDhMoi26rjLn9GexWhX3jnui2tKZ/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-07-13 13:58:55,078: INFO: 1254779870: Downloaded data from https://drive.google.com/file/d/11Ub5SDhMoi26rjLn9GexWhX3jnui2tKZ/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-07-13 14:32:28,054: INFO: main: >>>>> stage Data Ingestion Stage started <<<<<<<]
[2024-07-13 14:32:28,055: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-13 14:32:28,057: INFO: common: yaml file: params.yaml  loaded successfully]
[2024-07-13 14:32:28,058: INFO: common: created directory at: artifacts]
[2024-07-13 14:32:28,058: INFO: common: created directory at: artifacts/data_ingestion]
[2024-07-13 14:32:28,058: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/11Ub5SDhMoi26rjLn9GexWhX3jnui2tKZ/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-07-13 14:32:39,681: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/11Ub5SDhMoi26rjLn9GexWhX3jnui2tKZ/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-07-13 14:32:40,132: INFO: main: >>>>> stage Data Ingestion Stage completed <<<<<<

x========x]
[2024-07-13 20:10:24,817: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-13 20:10:24,820: INFO: common: yaml file: params.yaml  loaded successfully]
[2024-07-13 20:10:24,821: INFO: common: created directory at: artifacts]
[2024-07-13 20:10:24,822: INFO: common: created directory at: artifacts/data_ingestion]
[2024-07-13 20:10:24,823: INFO: 1254779870: Downloading data from https://drive.google.com/file/d/11Ub5SDhMoi26rjLn9GexWhX3jnui2tKZ/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-07-13 20:10:35,469: INFO: 1254779870: Downloaded data from https://drive.google.com/file/d/11Ub5SDhMoi26rjLn9GexWhX3jnui2tKZ/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-07-13 23:13:13,538: INFO: main: >>>>> stage Data Ingestion Stage started <<<<<<<]
[2024-07-13 23:13:13,540: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-13 23:13:13,542: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-13 23:13:13,543: INFO: common: created directory at: artifacts]
[2024-07-13 23:13:13,543: INFO: common: created directory at: artifacts/data_ingestion]
[2024-07-13 23:13:13,543: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/11Ub5SDhMoi26rjLn9GexWhX3jnui2tKZ/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-07-13 23:13:24,451: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/11Ub5SDhMoi26rjLn9GexWhX3jnui2tKZ/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-07-13 23:13:24,837: INFO: main: >>>>> stage Data Ingestion Stage completed <<<<<<

x========x]
[2024-07-13 23:13:24,838: INFO: main: ***************]
[2024-07-13 23:13:24,838: INFO: main: >>>> stage Prepare Base Model started <<<<<<<]
[2024-07-13 23:13:24,842: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-13 23:13:24,843: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-13 23:13:24,843: INFO: common: created directory at: artifacts]
[2024-07-13 23:13:24,844: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-07-13 23:13:25,206: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-07-13 23:13:25,363: INFO: main: >>>>> stage Prepare Base Model completed <<<<<<

x======x]
[2024-07-14 00:33:14,413: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-14 00:33:14,415: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-14 00:33:14,416: INFO: common: created directory at: artifacts]
[2024-07-14 00:33:14,417: INFO: common: created directory at: artifacts\training]
[2024-07-14 00:47:54,691: INFO: main: >>>>> stage Data Ingestion Stage started <<<<<<<]
[2024-07-14 00:47:54,694: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-14 00:47:54,696: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-14 00:47:54,696: INFO: common: created directory at: artifacts]
[2024-07-14 00:47:54,696: INFO: common: created directory at: artifacts/data_ingestion]
[2024-07-14 00:47:54,697: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/11Ub5SDhMoi26rjLn9GexWhX3jnui2tKZ/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-07-14 00:48:03,070: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/11Ub5SDhMoi26rjLn9GexWhX3jnui2tKZ/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-07-14 00:48:03,570: INFO: main: >>>>> stage Data Ingestion Stage completed <<<<<<

x========x]
[2024-07-14 00:48:03,570: INFO: main: ***************]
[2024-07-14 00:48:03,570: INFO: main: >>>> stage Prepare Base Model started <<<<<<<]
[2024-07-14 00:48:03,574: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-14 00:48:03,575: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-14 00:48:03,576: INFO: common: created directory at: artifacts]
[2024-07-14 00:48:03,576: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-07-14 00:48:04,074: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-07-14 00:48:04,278: INFO: main: >>>>> stage Prepare Base Model completed <<<<<<

x======x]
[2024-07-14 00:48:04,279: INFO: main: *******************]
[2024-07-14 00:48:04,279: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-07-14 00:48:04,279: ERROR: main: name 'ModelTrainingPipeline' is not defined]
Traceback (most recent call last):
  File "main.py", line 35, in <module>
    obj = ModelTrainingPipeline()
NameError: name 'ModelTrainingPipeline' is not defined
[2024-07-14 00:50:17,945: INFO: main: >>>>> stage Data Ingestion Stage started <<<<<<<]
[2024-07-14 00:50:17,947: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-14 00:50:17,949: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-14 00:50:17,949: INFO: common: created directory at: artifacts]
[2024-07-14 00:50:17,949: INFO: common: created directory at: artifacts/data_ingestion]
[2024-07-14 00:50:17,949: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/11Ub5SDhMoi26rjLn9GexWhX3jnui2tKZ/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-07-14 00:50:26,256: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/11Ub5SDhMoi26rjLn9GexWhX3jnui2tKZ/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-07-14 00:50:26,733: INFO: main: >>>>> stage Data Ingestion Stage completed <<<<<<

x========x]
[2024-07-14 00:50:26,733: INFO: main: ***************]
[2024-07-14 00:50:26,733: INFO: main: >>>> stage Prepare Base Model started <<<<<<<]
[2024-07-14 00:50:26,736: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-14 00:50:26,737: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-14 00:50:26,738: INFO: common: created directory at: artifacts]
[2024-07-14 00:50:26,738: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-07-14 00:50:27,147: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-07-14 00:50:27,361: INFO: main: >>>>> stage Prepare Base Model completed <<<<<<

x======x]
[2024-07-14 00:50:27,361: INFO: main: *******************]
[2024-07-14 00:50:27,361: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-07-14 00:50:27,363: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-14 00:50:27,365: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-14 00:50:27,366: INFO: common: created directory at: artifacts]
[2024-07-14 00:50:27,366: INFO: common: created directory at: artifacts\training]
[2024-07-14 00:51:02,107: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-07-14 11:05:53,731: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-14 11:05:53,742: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-14 11:05:53,744: INFO: common: created directory at: artifacts]
[2024-07-14 11:06:04,940: INFO: common: json file saved at: scores.json]
[2024-07-14 11:06:10,938: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-14 11:06:10,940: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-14 11:06:10,942: INFO: common: created directory at: artifacts]
[2024-07-14 11:06:21,845: INFO: common: json file saved at: scores.json]
[2024-07-14 11:06:23,278: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-07-14 11:06:24,253: INFO: builder_impl: Assets written to: C:\Users\nisha\AppData\Local\Temp\tmpdjr7wflp\model\data\model\assets]
[2024-07-14 11:06:33,992: INFO: dir_util: creating D:\Projects\Chest-Disease-Classification--MLFlow-DVC-MLOps-Deployment-\mlruns\0\edb00ca7c28045dd911124ebaf175637\artifacts\model\data]
[2024-07-14 11:06:33,994: INFO: dir_util: creating D:\Projects\Chest-Disease-Classification--MLFlow-DVC-MLOps-Deployment-\mlruns\0\edb00ca7c28045dd911124ebaf175637\artifacts\model\data\model]
[2024-07-14 11:06:33,996: INFO: dir_util: creating D:\Projects\Chest-Disease-Classification--MLFlow-DVC-MLOps-Deployment-\mlruns\0\edb00ca7c28045dd911124ebaf175637\artifacts\model\data\model\assets]
[2024-07-14 11:06:33,999: INFO: dir_util: creating D:\Projects\Chest-Disease-Classification--MLFlow-DVC-MLOps-Deployment-\mlruns\0\edb00ca7c28045dd911124ebaf175637\artifacts\model\data\model\variables]
[2024-07-14 11:24:26,067: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-14 11:24:26,071: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-14 11:24:26,073: INFO: common: created directory at: artifacts]
[2024-07-14 11:24:36,080: INFO: common: json file saved at: scores.json]
[2024-07-14 11:24:38,414: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-07-14 11:24:39,069: INFO: builder_impl: Assets written to: C:\Users\nisha\AppData\Local\Temp\tmp8s2r32he\model\data\model\assets]
[2024-07-14 11:36:12,868: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-14 11:36:12,871: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-14 11:36:12,872: INFO: common: created directory at: artifacts]
[2024-07-14 11:36:23,345: INFO: common: json file saved at: scores.json]
[2024-07-14 11:36:23,380: WARNING: connectionpool: Retrying (Retry(total=4, connect=5, read=4, redirect=5, status=5)) after connection broken by 'ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)': /nishantrv/Chest-Disease-Classification--MLFlow-DVC-MLOps-Deployment-.mlflow/api/2.0/mlflow/runs/create]
[2024-07-14 11:36:25,107: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-07-14 11:36:25,683: INFO: builder_impl: Assets written to: C:\Users\nisha\AppData\Local\Temp\tmpl3jywd1h\model\data\model\assets]
[2024-07-14 12:05:55,658: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-14 12:05:55,666: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-14 12:05:55,667: INFO: common: created directory at: artifacts]
[2024-07-14 12:06:05,552: INFO: common: json file saved at: scores.json]
[2024-07-14 12:06:05,577: WARNING: connectionpool: Retrying (Retry(total=4, connect=5, read=4, redirect=5, status=5)) after connection broken by 'ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)': /nishantrv/Chest-Disease-Classification--MLFlow-DVC-MLOps-Deployment-.mlflow/api/2.0/mlflow/runs/create]
[2024-07-14 12:06:07,523: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-07-14 12:06:08,369: INFO: builder_impl: Assets written to: C:\Users\nisha\AppData\Local\Temp\tmpu37esvtg\model\data\model\assets]
[2024-07-14 12:07:02,422: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-14 12:07:02,425: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-14 12:07:02,426: INFO: common: created directory at: artifacts]
[2024-07-14 12:07:12,447: INFO: common: json file saved at: scores.json]
[2024-07-14 12:07:14,370: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-07-14 12:07:15,025: INFO: builder_impl: Assets written to: C:\Users\nisha\AppData\Local\Temp\tmpvzr1iu3w\model\data\model\assets]
[2024-07-14 12:09:01,809: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-14 12:09:01,813: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-14 12:09:01,814: INFO: common: created directory at: artifacts]
[2024-07-14 12:09:12,279: INFO: common: json file saved at: scores.json]
[2024-07-14 12:09:14,212: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-07-14 12:09:14,835: INFO: builder_impl: Assets written to: C:\Users\nisha\AppData\Local\Temp\tmphgmb4tg7\model\data\model\assets]
[2024-07-14 12:10:25,241: WARNING: save: Found untraced functions such as _update_step_xla while saving (showing 1 of 1). These functions will not be directly callable after loading.]
[2024-07-14 12:10:25,481: INFO: builder_impl: Assets written to: C:\Users\nisha\AppData\Local\Temp\tmplbnge13o\model\data\model\assets]
[2024-07-14 12:16:36,768: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-14 12:16:36,771: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-14 12:16:36,772: INFO: common: created directory at: artifacts]
[2024-07-14 12:16:47,193: INFO: common: json file saved at: scores.json]
[2024-07-14 12:16:49,489: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-07-14 12:16:50,180: INFO: builder_impl: Assets written to: C:\Users\nisha\AppData\Local\Temp\tmp3h9pfq15\model\data\model\assets]
[2024-07-14 12:33:58,832: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-14 12:33:58,834: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-14 12:33:58,836: INFO: common: created directory at: artifacts]
[2024-07-14 12:34:10,869: INFO: common: json file saved at: scores.json]
[2024-07-14 12:34:10,910: WARNING: connectionpool: Retrying (Retry(total=4, connect=5, read=4, redirect=5, status=5)) after connection broken by 'ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)': /nishantrv/Chest-Disease-Classification--MLFlow-DVC-MLOps-Deployment-.mlflow/api/2.0/mlflow/runs/create]
[2024-07-14 12:34:13,460: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-07-14 12:34:14,238: INFO: builder_impl: Assets written to: C:\Users\nisha\AppData\Local\Temp\tmpifkp5am0\model\data\model\assets]
[2024-07-14 12:34:50,712: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-14 12:34:50,715: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-14 12:34:50,716: INFO: common: created directory at: artifacts]
[2024-07-14 12:35:03,860: INFO: common: json file saved at: scores.json]
[2024-07-14 12:36:00,021: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-14 12:36:00,025: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-14 12:36:00,026: INFO: common: created directory at: artifacts]
[2024-07-14 12:36:13,363: INFO: common: json file saved at: scores.json]
[2024-07-14 12:36:16,270: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-07-14 12:36:16,982: INFO: builder_impl: Assets written to: C:\Users\nisha\AppData\Local\Temp\tmpt3g8obmj\model\data\model\assets]
[2024-07-14 13:04:45,371: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-14 13:04:45,374: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-14 13:04:45,376: INFO: common: created directory at: artifacts]
[2024-07-14 13:04:57,003: INFO: common: json file saved at: scores.json]
[2024-07-14 13:04:59,988: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-07-14 13:05:00,887: INFO: builder_impl: Assets written to: C:\Users\nisha\AppData\Local\Temp\tmpn6v0c_l7\model\data\model\assets]
[2024-07-14 13:15:02,944: INFO: main: >>>>> stage Data Ingestion Stage started <<<<<<<]
[2024-07-14 13:15:02,947: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-14 13:15:02,953: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-14 13:15:02,954: INFO: common: created directory at: artifacts]
[2024-07-14 13:15:02,954: INFO: common: created directory at: artifacts/data_ingestion]
[2024-07-14 13:15:02,954: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/11Ub5SDhMoi26rjLn9GexWhX3jnui2tKZ/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-07-14 13:15:15,440: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/11Ub5SDhMoi26rjLn9GexWhX3jnui2tKZ/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-07-14 13:15:15,907: INFO: main: >>>>> stage Data Ingestion Stage completed <<<<<<

x========x]
[2024-07-14 13:15:15,908: INFO: main: ***************]
[2024-07-14 13:15:15,908: INFO: main: >>>> stage Prepare Base Model started <<<<<<<]
[2024-07-14 13:15:15,910: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-14 13:15:15,914: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-14 13:15:15,915: INFO: common: created directory at: artifacts]
[2024-07-14 13:15:15,915: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-07-14 13:15:16,312: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-07-14 13:15:16,501: INFO: main: >>>>> stage Prepare Base Model completed <<<<<<

x======x]
[2024-07-14 13:15:16,501: INFO: main: *******************]
[2024-07-14 13:15:16,501: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-07-14 13:15:16,503: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-14 13:15:16,505: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-14 13:15:16,505: INFO: common: created directory at: artifacts]
[2024-07-14 13:15:16,506: INFO: common: created directory at: artifacts\training]
[2024-07-14 13:15:50,780: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-07-14 13:15:50,780: INFO: main: *******************]
[2024-07-14 13:15:50,780: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2024-07-14 13:15:50,783: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-14 13:15:50,784: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-14 13:15:50,785: INFO: common: created directory at: artifacts]
[2024-07-14 13:16:01,745: INFO: common: json file saved at: scores.json]
[2024-07-14 13:16:01,746: INFO: common: json file saved at: scores.json]
[2024-07-14 13:16:01,746: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2024-07-14 13:21:08,584: INFO: main: >>>>> stage Data Ingestion Stage started <<<<<<<]
[2024-07-14 13:21:08,587: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-14 13:21:08,589: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-14 13:21:08,589: INFO: common: created directory at: artifacts]
[2024-07-14 13:21:08,589: INFO: common: created directory at: artifacts/data_ingestion]
[2024-07-14 13:21:08,590: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/11Ub5SDhMoi26rjLn9GexWhX3jnui2tKZ/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-07-14 13:21:26,140: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/11Ub5SDhMoi26rjLn9GexWhX3jnui2tKZ/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-07-14 13:21:26,577: INFO: main: >>>>> stage Data Ingestion Stage completed <<<<<<

x========x]
[2024-07-14 13:21:26,578: INFO: main: ***************]
[2024-07-14 13:21:26,578: INFO: main: >>>> stage Prepare Base Model started <<<<<<<]
[2024-07-14 13:21:26,580: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-14 13:21:26,582: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-14 13:21:26,582: INFO: common: created directory at: artifacts]
[2024-07-14 13:21:26,582: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-07-14 13:21:26,975: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-07-14 13:21:27,168: INFO: main: >>>>> stage Prepare Base Model completed <<<<<<

x======x]
[2024-07-14 13:21:27,168: INFO: main: *******************]
[2024-07-14 13:21:27,168: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-07-14 13:21:27,171: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-14 13:21:27,173: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-14 13:21:27,174: INFO: common: created directory at: artifacts]
[2024-07-14 13:21:27,174: INFO: common: created directory at: artifacts\training]
[2024-07-14 13:22:00,198: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-07-14 13:22:00,198: INFO: main: *******************]
[2024-07-14 13:22:00,198: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2024-07-14 13:22:00,200: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-14 13:22:00,202: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-14 13:22:00,202: INFO: common: created directory at: artifacts]
[2024-07-14 13:22:10,697: INFO: common: json file saved at: scores.json]
[2024-07-14 13:22:10,698: INFO: common: json file saved at: scores.json]
[2024-07-14 13:22:10,698: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2024-07-14 13:36:34,012: INFO: main: >>>>> stage Data Ingestion Stage started <<<<<<<]
[2024-07-14 13:36:34,015: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-14 13:36:34,016: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-14 13:36:34,017: INFO: common: created directory at: artifacts]
[2024-07-14 13:36:34,017: INFO: common: created directory at: artifacts/data_ingestion]
[2024-07-14 13:36:34,017: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/11Ub5SDhMoi26rjLn9GexWhX3jnui2tKZ/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-07-14 13:36:45,685: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/11Ub5SDhMoi26rjLn9GexWhX3jnui2tKZ/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-07-14 13:36:46,088: INFO: main: >>>>> stage Data Ingestion Stage completed <<<<<<

x========x]
[2024-07-14 13:36:46,088: INFO: main: ***************]
[2024-07-14 13:36:46,088: INFO: main: >>>> stage Prepare Base Model started <<<<<<<]
[2024-07-14 13:36:46,091: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-14 13:36:46,092: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-14 13:36:46,092: INFO: common: created directory at: artifacts]
[2024-07-14 13:36:46,093: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-07-14 13:36:46,470: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-07-14 13:36:46,667: INFO: main: >>>>> stage Prepare Base Model completed <<<<<<

x======x]
[2024-07-14 13:36:46,667: INFO: main: *******************]
[2024-07-14 13:36:46,667: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-07-14 13:36:46,670: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-14 13:36:46,672: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-14 13:36:46,673: INFO: common: created directory at: artifacts]
[2024-07-14 13:36:46,673: INFO: common: created directory at: artifacts\training]
[2024-07-14 13:37:18,665: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-07-14 13:37:18,666: INFO: main: *******************]
[2024-07-14 13:37:18,666: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2024-07-14 13:37:18,668: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-14 13:37:18,670: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-14 13:37:18,671: INFO: common: created directory at: artifacts]
[2024-07-14 13:37:29,131: INFO: common: json file saved at: scores.json]
[2024-07-14 13:37:29,132: INFO: common: json file saved at: scores.json]
[2024-07-14 13:37:29,628: ERROR: main: INVALID_PARAMETER_VALUE: Response: {'error_code': 'INVALID_PARAMETER_VALUE'}]
Traceback (most recent call last):
  File "main.py", line 49, in <module>
    model_evalution.main()
  File "d:\projects\chest-disease-classification--mlflow-dvc-mlops-deployment-\src\cnnClassifier\pipeline\stage_04_model_evaluation.py", line 20, in main
    evaluation.log_into_mlflow()
  File "d:\projects\chest-disease-classification--mlflow-dvc-mlops-deployment-\src\cnnClassifier\components\model_evaluation.py", line 60, in log_into_mlflow
    with mlflow.start_run():
  File "C:\Users\nisha\Anaconda3\envs\c1\lib\site-packages\mlflow\tracking\fluent.py", line 350, in start_run
    active_run_obj = client.create_run(
  File "C:\Users\nisha\Anaconda3\envs\c1\lib\site-packages\mlflow\tracking\client.py", line 275, in create_run
    return self._tracking_client.create_run(experiment_id, start_time, tags, run_name)
  File "C:\Users\nisha\Anaconda3\envs\c1\lib\site-packages\mlflow\tracking\_tracking_service\client.py", line 131, in create_run
    return self.store.create_run(
  File "C:\Users\nisha\Anaconda3\envs\c1\lib\site-packages\mlflow\store\tracking\rest_store.py", line 175, in create_run
    response_proto = self._call_endpoint(CreateRun, req_body)
  File "C:\Users\nisha\Anaconda3\envs\c1\lib\site-packages\mlflow\store\tracking\rest_store.py", line 56, in _call_endpoint
    return call_endpoint(self.get_host_creds(), endpoint, method, json_body, response_proto)
  File "C:\Users\nisha\Anaconda3\envs\c1\lib\site-packages\mlflow\utils\rest_utils.py", line 281, in call_endpoint
    response = verify_rest_response(response, endpoint)
  File "C:\Users\nisha\Anaconda3\envs\c1\lib\site-packages\mlflow\utils\rest_utils.py", line 207, in verify_rest_response
    raise RestException(json.loads(response.text))
mlflow.exceptions.RestException: INVALID_PARAMETER_VALUE: Response: {'error_code': 'INVALID_PARAMETER_VALUE'}
[2024-07-14 13:38:10,783: INFO: main: >>>>> stage Data Ingestion Stage started <<<<<<<]
[2024-07-14 13:38:10,786: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-14 13:38:10,787: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-14 13:38:10,788: INFO: common: created directory at: artifacts]
[2024-07-14 13:38:10,788: INFO: common: created directory at: artifacts/data_ingestion]
[2024-07-14 13:38:10,788: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/11Ub5SDhMoi26rjLn9GexWhX3jnui2tKZ/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-07-14 13:38:20,842: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/11Ub5SDhMoi26rjLn9GexWhX3jnui2tKZ/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-07-14 13:38:21,272: INFO: main: >>>>> stage Data Ingestion Stage completed <<<<<<

x========x]
[2024-07-14 13:38:21,272: INFO: main: ***************]
[2024-07-14 13:38:21,272: INFO: main: >>>> stage Prepare Base Model started <<<<<<<]
[2024-07-14 13:38:21,274: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-14 13:38:21,276: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-14 13:38:21,277: INFO: common: created directory at: artifacts]
[2024-07-14 13:38:21,277: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-07-14 13:38:21,707: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-07-14 13:38:21,913: INFO: main: >>>>> stage Prepare Base Model completed <<<<<<

x======x]
[2024-07-14 13:38:21,913: INFO: main: *******************]
[2024-07-14 13:38:21,913: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-07-14 13:38:21,915: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-14 13:38:21,917: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-14 13:38:21,917: INFO: common: created directory at: artifacts]
[2024-07-14 13:38:21,918: INFO: common: created directory at: artifacts\training]
[2024-07-14 13:38:53,410: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-07-14 13:38:53,410: INFO: main: *******************]
[2024-07-14 13:38:53,410: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2024-07-14 13:38:53,412: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-14 13:38:53,414: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-14 13:38:53,414: INFO: common: created directory at: artifacts]
[2024-07-14 13:39:03,816: INFO: common: json file saved at: scores.json]
[2024-07-14 13:39:03,818: INFO: common: json file saved at: scores.json]
[2024-07-14 13:39:04,251: ERROR: main: INVALID_PARAMETER_VALUE: Response: {'error_code': 'INVALID_PARAMETER_VALUE'}]
Traceback (most recent call last):
  File "main.py", line 49, in <module>
    model_evalution.main()
  File "d:\projects\chest-disease-classification--mlflow-dvc-mlops-deployment-\src\cnnClassifier\pipeline\stage_04_model_evaluation.py", line 20, in main
    evaluation.log_into_mlflow()
  File "d:\projects\chest-disease-classification--mlflow-dvc-mlops-deployment-\src\cnnClassifier\components\model_evaluation.py", line 60, in log_into_mlflow
    with mlflow.start_run():
  File "C:\Users\nisha\Anaconda3\envs\c1\lib\site-packages\mlflow\tracking\fluent.py", line 350, in start_run
    active_run_obj = client.create_run(
  File "C:\Users\nisha\Anaconda3\envs\c1\lib\site-packages\mlflow\tracking\client.py", line 275, in create_run
    return self._tracking_client.create_run(experiment_id, start_time, tags, run_name)
  File "C:\Users\nisha\Anaconda3\envs\c1\lib\site-packages\mlflow\tracking\_tracking_service\client.py", line 131, in create_run
    return self.store.create_run(
  File "C:\Users\nisha\Anaconda3\envs\c1\lib\site-packages\mlflow\store\tracking\rest_store.py", line 175, in create_run
    response_proto = self._call_endpoint(CreateRun, req_body)
  File "C:\Users\nisha\Anaconda3\envs\c1\lib\site-packages\mlflow\store\tracking\rest_store.py", line 56, in _call_endpoint
    return call_endpoint(self.get_host_creds(), endpoint, method, json_body, response_proto)
  File "C:\Users\nisha\Anaconda3\envs\c1\lib\site-packages\mlflow\utils\rest_utils.py", line 281, in call_endpoint
    response = verify_rest_response(response, endpoint)
  File "C:\Users\nisha\Anaconda3\envs\c1\lib\site-packages\mlflow\utils\rest_utils.py", line 207, in verify_rest_response
    raise RestException(json.loads(response.text))
mlflow.exceptions.RestException: INVALID_PARAMETER_VALUE: Response: {'error_code': 'INVALID_PARAMETER_VALUE'}
[2024-07-14 13:48:41,704: INFO: main: >>>>> stage Data Ingestion Stage started <<<<<<<]
[2024-07-14 13:48:41,706: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-14 13:48:41,708: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-14 13:48:41,708: INFO: common: created directory at: artifacts]
[2024-07-14 13:48:41,709: INFO: common: created directory at: artifacts/data_ingestion]
[2024-07-14 13:48:41,709: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/11Ub5SDhMoi26rjLn9GexWhX3jnui2tKZ/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-07-14 13:48:54,279: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/11Ub5SDhMoi26rjLn9GexWhX3jnui2tKZ/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-07-14 13:48:54,864: INFO: main: >>>>> stage Data Ingestion Stage completed <<<<<<

x========x]
[2024-07-14 13:48:54,865: INFO: main: ***************]
[2024-07-14 13:48:54,865: INFO: main: >>>> stage Prepare Base Model started <<<<<<<]
[2024-07-14 13:48:54,871: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-14 13:48:54,874: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-14 13:48:54,875: INFO: common: created directory at: artifacts]
[2024-07-14 13:48:54,875: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-07-14 13:48:55,342: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-07-14 13:48:55,561: INFO: main: >>>>> stage Prepare Base Model completed <<<<<<

x======x]
[2024-07-14 13:48:55,561: INFO: main: *******************]
[2024-07-14 13:48:55,561: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-07-14 13:48:55,564: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-14 13:48:55,567: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-14 13:48:55,568: INFO: common: created directory at: artifacts]
[2024-07-14 13:48:55,568: INFO: common: created directory at: artifacts\training]
[2024-07-14 13:49:35,823: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-07-14 13:49:35,823: INFO: main: *******************]
[2024-07-14 13:49:35,823: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2024-07-14 13:49:35,826: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-14 13:49:35,828: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-14 13:49:35,828: INFO: common: created directory at: artifacts]
[2024-07-14 13:49:47,841: INFO: common: json file saved at: scores.json]
[2024-07-14 13:49:47,842: INFO: common: json file saved at: scores.json]
[2024-07-14 13:49:48,307: ERROR: main: INVALID_PARAMETER_VALUE: Response: {'error_code': 'INVALID_PARAMETER_VALUE'}]
Traceback (most recent call last):
  File "main.py", line 49, in <module>
    model_evalution.main()
  File "d:\projects\chest-disease-classification--mlflow-dvc-mlops-deployment-\src\cnnClassifier\pipeline\stage_04_model_evaluation.py", line 20, in main
    evaluation.log_into_mlflow()
  File "d:\projects\chest-disease-classification--mlflow-dvc-mlops-deployment-\src\cnnClassifier\components\model_evaluation.py", line 60, in log_into_mlflow
    with mlflow.start_run():
  File "C:\Users\nisha\Anaconda3\envs\c1\lib\site-packages\mlflow\tracking\fluent.py", line 350, in start_run
    active_run_obj = client.create_run(
  File "C:\Users\nisha\Anaconda3\envs\c1\lib\site-packages\mlflow\tracking\client.py", line 275, in create_run
    return self._tracking_client.create_run(experiment_id, start_time, tags, run_name)
  File "C:\Users\nisha\Anaconda3\envs\c1\lib\site-packages\mlflow\tracking\_tracking_service\client.py", line 131, in create_run
    return self.store.create_run(
  File "C:\Users\nisha\Anaconda3\envs\c1\lib\site-packages\mlflow\store\tracking\rest_store.py", line 175, in create_run
    response_proto = self._call_endpoint(CreateRun, req_body)
  File "C:\Users\nisha\Anaconda3\envs\c1\lib\site-packages\mlflow\store\tracking\rest_store.py", line 56, in _call_endpoint
    return call_endpoint(self.get_host_creds(), endpoint, method, json_body, response_proto)
  File "C:\Users\nisha\Anaconda3\envs\c1\lib\site-packages\mlflow\utils\rest_utils.py", line 281, in call_endpoint
    response = verify_rest_response(response, endpoint)
  File "C:\Users\nisha\Anaconda3\envs\c1\lib\site-packages\mlflow\utils\rest_utils.py", line 207, in verify_rest_response
    raise RestException(json.loads(response.text))
mlflow.exceptions.RestException: INVALID_PARAMETER_VALUE: Response: {'error_code': 'INVALID_PARAMETER_VALUE'}
[2024-07-14 13:52:37,737: INFO: main: >>>>> stage Data Ingestion Stage started <<<<<<<]
[2024-07-14 13:52:37,741: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-14 13:52:37,744: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-14 13:52:37,744: INFO: common: created directory at: artifacts]
[2024-07-14 13:52:37,744: INFO: common: created directory at: artifacts/data_ingestion]
[2024-07-14 13:52:37,745: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/11Ub5SDhMoi26rjLn9GexWhX3jnui2tKZ/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-07-14 13:52:49,423: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/11Ub5SDhMoi26rjLn9GexWhX3jnui2tKZ/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-07-14 13:52:49,878: INFO: main: >>>>> stage Data Ingestion Stage completed <<<<<<

x========x]
[2024-07-14 13:52:49,878: INFO: main: ***************]
[2024-07-14 13:52:49,878: INFO: main: >>>> stage Prepare Base Model started <<<<<<<]
[2024-07-14 13:52:49,881: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-14 13:52:49,882: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-14 13:52:49,883: INFO: common: created directory at: artifacts]
[2024-07-14 13:52:49,883: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-07-14 13:52:50,333: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-07-14 13:52:50,566: INFO: main: >>>>> stage Prepare Base Model completed <<<<<<

x======x]
[2024-07-14 13:52:50,566: INFO: main: *******************]
[2024-07-14 13:52:50,566: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-07-14 13:52:50,569: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-14 13:52:50,571: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-14 13:52:50,571: INFO: common: created directory at: artifacts]
[2024-07-14 13:52:50,572: INFO: common: created directory at: artifacts\training]
[2024-07-14 13:53:28,968: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-07-14 13:53:28,969: INFO: main: *******************]
[2024-07-14 13:53:28,969: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2024-07-14 13:53:28,971: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-14 13:53:28,972: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-14 13:53:28,973: INFO: common: created directory at: artifacts]
[2024-07-14 13:53:41,462: INFO: common: json file saved at: scores.json]
[2024-07-14 13:53:41,463: INFO: common: json file saved at: scores.json]
[2024-07-14 13:53:41,965: ERROR: main: INVALID_PARAMETER_VALUE: Response: {'error_code': 'INVALID_PARAMETER_VALUE'}]
Traceback (most recent call last):
  File "main.py", line 49, in <module>
    model_evalution.main()
  File "d:\projects\chest-disease-classification--mlflow-dvc-mlops-deployment-\src\cnnClassifier\pipeline\stage_04_model_evaluation.py", line 20, in main
    evaluation.log_into_mlflow()
  File "d:\projects\chest-disease-classification--mlflow-dvc-mlops-deployment-\src\cnnClassifier\components\model_evaluation.py", line 60, in log_into_mlflow
    with mlflow.start_run():
  File "C:\Users\nisha\Anaconda3\envs\c1\lib\site-packages\mlflow\tracking\fluent.py", line 350, in start_run
    active_run_obj = client.create_run(
  File "C:\Users\nisha\Anaconda3\envs\c1\lib\site-packages\mlflow\tracking\client.py", line 275, in create_run
    return self._tracking_client.create_run(experiment_id, start_time, tags, run_name)
  File "C:\Users\nisha\Anaconda3\envs\c1\lib\site-packages\mlflow\tracking\_tracking_service\client.py", line 131, in create_run
    return self.store.create_run(
  File "C:\Users\nisha\Anaconda3\envs\c1\lib\site-packages\mlflow\store\tracking\rest_store.py", line 175, in create_run
    response_proto = self._call_endpoint(CreateRun, req_body)
  File "C:\Users\nisha\Anaconda3\envs\c1\lib\site-packages\mlflow\store\tracking\rest_store.py", line 56, in _call_endpoint
    return call_endpoint(self.get_host_creds(), endpoint, method, json_body, response_proto)
  File "C:\Users\nisha\Anaconda3\envs\c1\lib\site-packages\mlflow\utils\rest_utils.py", line 281, in call_endpoint
    response = verify_rest_response(response, endpoint)
  File "C:\Users\nisha\Anaconda3\envs\c1\lib\site-packages\mlflow\utils\rest_utils.py", line 207, in verify_rest_response
    raise RestException(json.loads(response.text))
mlflow.exceptions.RestException: INVALID_PARAMETER_VALUE: Response: {'error_code': 'INVALID_PARAMETER_VALUE'}
[2024-07-14 17:05:43,761: INFO: main: >>>>> stage Data Ingestion Stage started <<<<<<<]
[2024-07-14 17:05:43,763: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-14 17:05:43,765: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-14 17:05:43,766: INFO: common: created directory at: artifacts]
[2024-07-14 17:05:43,766: INFO: common: created directory at: artifacts/data_ingestion]
[2024-07-14 17:05:43,766: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/11Ub5SDhMoi26rjLn9GexWhX3jnui2tKZ/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-07-14 17:05:51,707: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/11Ub5SDhMoi26rjLn9GexWhX3jnui2tKZ/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-07-14 17:05:52,087: INFO: main: >>>>> stage Data Ingestion Stage completed <<<<<<

x========x]
[2024-07-14 17:05:52,087: INFO: main: ***************]
[2024-07-14 17:05:52,087: INFO: main: >>>> stage Prepare Base Model started <<<<<<<]
[2024-07-14 17:05:52,090: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-14 17:05:52,091: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-14 17:05:52,092: INFO: common: created directory at: artifacts]
[2024-07-14 17:05:52,092: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-07-14 17:05:52,426: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-07-14 17:05:52,631: INFO: main: >>>>> stage Prepare Base Model completed <<<<<<

x======x]
[2024-07-14 17:05:52,631: INFO: main: *******************]
[2024-07-14 17:05:52,631: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-07-14 17:05:52,633: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-14 17:05:52,634: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-14 17:05:52,635: INFO: common: created directory at: artifacts]
[2024-07-14 17:05:52,635: INFO: common: created directory at: artifacts\training]
[2024-07-14 17:07:00,147: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-07-14 17:07:00,148: INFO: main: *******************]
[2024-07-14 17:07:00,148: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2024-07-14 17:07:00,152: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-14 17:07:00,156: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-14 17:07:00,156: INFO: common: created directory at: artifacts]
[2024-07-14 17:07:18,228: INFO: common: json file saved at: scores.json]
[2024-07-14 17:07:18,229: INFO: common: json file saved at: scores.json]
[2024-07-14 17:07:18,886: ERROR: main: INVALID_PARAMETER_VALUE: Response: {'error_code': 'INVALID_PARAMETER_VALUE'}]
Traceback (most recent call last):
  File "main.py", line 49, in <module>
    model_evalution.main()
  File "d:\projects\chest-disease-classification--mlflow-dvc-mlops-deployment-\src\cnnClassifier\pipeline\stage_04_model_evaluation.py", line 20, in main
    evaluation.log_into_mlflow()
  File "d:\projects\chest-disease-classification--mlflow-dvc-mlops-deployment-\src\cnnClassifier\components\model_evaluation.py", line 60, in log_into_mlflow
    with mlflow.start_run():
  File "C:\Users\nisha\Anaconda3\envs\c1\lib\site-packages\mlflow\tracking\fluent.py", line 350, in start_run
    active_run_obj = client.create_run(
  File "C:\Users\nisha\Anaconda3\envs\c1\lib\site-packages\mlflow\tracking\client.py", line 275, in create_run
    return self._tracking_client.create_run(experiment_id, start_time, tags, run_name)
  File "C:\Users\nisha\Anaconda3\envs\c1\lib\site-packages\mlflow\tracking\_tracking_service\client.py", line 131, in create_run
    return self.store.create_run(
  File "C:\Users\nisha\Anaconda3\envs\c1\lib\site-packages\mlflow\store\tracking\rest_store.py", line 175, in create_run
    response_proto = self._call_endpoint(CreateRun, req_body)
  File "C:\Users\nisha\Anaconda3\envs\c1\lib\site-packages\mlflow\store\tracking\rest_store.py", line 56, in _call_endpoint
    return call_endpoint(self.get_host_creds(), endpoint, method, json_body, response_proto)
  File "C:\Users\nisha\Anaconda3\envs\c1\lib\site-packages\mlflow\utils\rest_utils.py", line 281, in call_endpoint
    response = verify_rest_response(response, endpoint)
  File "C:\Users\nisha\Anaconda3\envs\c1\lib\site-packages\mlflow\utils\rest_utils.py", line 207, in verify_rest_response
    raise RestException(json.loads(response.text))
mlflow.exceptions.RestException: INVALID_PARAMETER_VALUE: Response: {'error_code': 'INVALID_PARAMETER_VALUE'}
[2024-07-14 17:10:02,124: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-07-14 17:10:02,127: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-14 17:10:02,129: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-14 17:10:02,130: INFO: common: created directory at: artifacts]
[2024-07-14 17:10:02,130: INFO: common: created directory at: artifacts/data_ingestion]
[2024-07-14 17:10:02,130: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/11Ub5SDhMoi26rjLn9GexWhX3jnui2tKZ/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-07-14 17:10:10,305: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/11Ub5SDhMoi26rjLn9GexWhX3jnui2tKZ/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-07-14 17:10:10,691: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-07-14 17:10:10,691: INFO: main: *******************]
[2024-07-14 17:10:10,692: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-07-14 17:10:10,694: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-14 17:10:10,695: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-14 17:10:10,696: INFO: common: created directory at: artifacts]
[2024-07-14 17:10:10,696: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-07-14 17:10:11,044: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-07-14 17:10:11,244: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-07-14 17:10:11,244: INFO: main: *******************]
[2024-07-14 17:10:11,244: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-07-14 17:10:11,246: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-14 17:10:11,247: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-14 17:10:11,247: INFO: common: created directory at: artifacts]
[2024-07-14 17:10:11,248: INFO: common: created directory at: artifacts\training]
[2024-07-14 17:11:02,118: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-07-14 17:11:02,119: INFO: main: *******************]
[2024-07-14 17:11:02,119: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2024-07-14 17:11:02,123: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-14 17:11:02,126: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-14 17:11:02,127: INFO: common: created directory at: artifacts]
[2024-07-14 17:11:18,582: INFO: common: json file saved at: scores.json]
[2024-07-14 17:11:18,583: INFO: common: json file saved at: scores.json]
[2024-07-14 17:11:19,169: ERROR: main: INVALID_PARAMETER_VALUE: Response: {'error_code': 'INVALID_PARAMETER_VALUE'}]
Traceback (most recent call last):
  File "main.py", line 57, in <module>
    model_evalution.main()
  File "d:\projects\chest-disease-classification--mlflow-dvc-mlops-deployment-\src\cnnClassifier\pipeline\stage_04_model_evaluation.py", line 20, in main
    evaluation.log_into_mlflow()
  File "d:\projects\chest-disease-classification--mlflow-dvc-mlops-deployment-\src\cnnClassifier\components\model_evaluation.py", line 60, in log_into_mlflow
    with mlflow.start_run():
  File "C:\Users\nisha\Anaconda3\envs\c1\lib\site-packages\mlflow\tracking\fluent.py", line 350, in start_run
    active_run_obj = client.create_run(
  File "C:\Users\nisha\Anaconda3\envs\c1\lib\site-packages\mlflow\tracking\client.py", line 275, in create_run
    return self._tracking_client.create_run(experiment_id, start_time, tags, run_name)
  File "C:\Users\nisha\Anaconda3\envs\c1\lib\site-packages\mlflow\tracking\_tracking_service\client.py", line 131, in create_run
    return self.store.create_run(
  File "C:\Users\nisha\Anaconda3\envs\c1\lib\site-packages\mlflow\store\tracking\rest_store.py", line 175, in create_run
    response_proto = self._call_endpoint(CreateRun, req_body)
  File "C:\Users\nisha\Anaconda3\envs\c1\lib\site-packages\mlflow\store\tracking\rest_store.py", line 56, in _call_endpoint
    return call_endpoint(self.get_host_creds(), endpoint, method, json_body, response_proto)
  File "C:\Users\nisha\Anaconda3\envs\c1\lib\site-packages\mlflow\utils\rest_utils.py", line 281, in call_endpoint
    response = verify_rest_response(response, endpoint)
  File "C:\Users\nisha\Anaconda3\envs\c1\lib\site-packages\mlflow\utils\rest_utils.py", line 207, in verify_rest_response
    raise RestException(json.loads(response.text))
mlflow.exceptions.RestException: INVALID_PARAMETER_VALUE: Response: {'error_code': 'INVALID_PARAMETER_VALUE'}
